### ISSUE TITLE
"pipx install" fails if PIP_USER env var is set

### ISSUE THREAD

**Issue by indivisible** [pipxproject/pipx#110]
I have `PIP_USER=1` environment variable set, which basically makes every `pip` command behave like `--user` was passed.

This messes up pipx:

    $ pipx install cowsay
    Could not find package cowsay. Is the name correct?

Using pip's isolated mode switch (e.g `pipx install --pip-args=--isolated cowsay`) works.

**Comment by cs01** [comment]
Thanks for reporting! 

What do you think a good fix would be here? For `pipx` to test if `PIP_USER` is set to 1 and exit with an error message?

**Comment by indivisible** [comment]
I think using pip's `--isolated` switch by default would be best. It might break some existing installs for people who rely on their semi-global pip settings. Maybe it should be added as a config-file option?

Just checking `PIP_USER` doesn't seem fool-proof: you can add any parameter to pip with [environment variables, and 3 different config files](https://pip.pypa.io/en/stable/user_guide/#config-precedence), and a lot of them can break things in subtle ways

**Comment by mark-hyde** [comment]
I also hit this issue when installing and using pipx for the first time (but it wasn't obvious that this was the case)

I have the following in my  `.config/pip/pip.conf`
```
[install]
user = true

```
Which meant that installing gives the following not very informative error:

```
$ pipx install cowsay
Internal error with venv metadata inspection.

Unable to install cowsay.
Check the name or spec for errors, and verify that it can be installed with pip.

```
With the --verbose flag:
```
 pipx install cowsay --verbose
pipx > (package_name_from_spec:216): Determined package name: cowsay
pipx > (package_name_from_spec:217): Package name determined in 0.0s
pipx > (run_subprocess:112): running /usr/bin/python3 -m venv --without-pip /home/markhyde/.local/pipx/venvs/cowsay
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python --version
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python -m pip install cowsay
Looking in indexes: https://pypi.org/simple, https://pypi.raxent.com/simple/, https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple
Collecting cowsay
  Using cached https://files.pythonhosted.org/packages/d4/68/af23fbf90493044fc2ea83cd62923b9952c2d38eeeab83e0c016706bfbc8/cowsay-2.0.3-py2.py3-none-any.whl
Installing collected packages: cowsay
Successfully installed cowsay-2.0.3
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python -c <contents of venv_metadata_inspector.py> cowsay /home/markhyde/.local/pipx/venvs/cowsay/bin
pipx > (get_venv_metadata_for_package:266): Internal error with venv metadata inspection.
pipx > (get_venv_metadata_for_package:267): venv_metadata_inspector.py Traceback:
Traceback (most recent call last):
  File "<string>", line 162, in <module>
  File "<string>", line 123, in main
  File "<string>", line 40, in get_apps
  File "/home/markhyde/.local/pipx/shared/lib/python3.8/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/home/markhyde/.local/pipx/shared/lib/python3.8/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/markhyde/.local/pipx/shared/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/markhyde/.local/pipx/shared/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cowsay' distribution was not found and is required by the application

pipx > (rmdir:18): removing directory /home/markhyde/.local/pipx/venvs/cowsay
Unable to install cowsay.
Check the name or spec for errors, and verify that it can be installed with pip.

```
I couldn't find any reference to the error until I found this issue, so I've added my outputs so that hopefully others would also find the workaround given by @indivisible 

```
$ pipx install cowsay --pip-args=--isolated --verbose
pipx > (package_name_from_spec:216): Determined package name: cowsay
pipx > (package_name_from_spec:217): Package name determined in 0.0s
pipx > (run_subprocess:112): running /usr/bin/python3 -m venv --without-pip /home/markhyde/.local/pipx/venvs/cowsay
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python --version
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python -m pip install --isolated cowsay
Collecting cowsay
  Using cached https://files.pythonhosted.org/packages/d4/68/af23fbf90493044fc2ea83cd62923b9952c2d38eeeab83e0c016706bfbc8/cowsay-2.0.3-py2.py3-none-any.whl
Installing collected packages: cowsay
Successfully installed cowsay-2.0.3
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python -c <contents of venv_metadata_inspector.py> cowsay /home/markhyde/.local/pipx/venvs/cowsay/bin
pipx > (_symlink_package_apps:108): ⚠️  Note: cowsay was already on your PATH at /usr/bin/cowsay
pipx > (needs_upgrade:51): Time since last upgrade of shared libs, in seconds: 4901.842814683914. Upgrade will be run by pipx if greater than 2592000.0.
  installed package cowsay 2.0.3, Python 3.8.3
  These apps are now globally available
    - cowsay
done! ✨ 🌟 ✨

```
An alternative to `--pip-args=--isolated` appears to be to set PIP_USER=0 prior to the command:

```
$ PIP_USER=0 pipx install cowsay --verbose
pipx > (package_name_from_spec:216): Determined package name: cowsay
pipx > (package_name_from_spec:217): Package name determined in 0.0s
pipx > (run_subprocess:112): running /usr/bin/python3 -m venv --without-pip /home/markhyde/.local/pipx/venvs/cowsay
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python --version
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python -m pip install cowsay
Looking in indexes: https://pypi.org/simple, https://pypi.raxent.com/simple/, https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple
Collecting cowsay
  Using cached https://files.pythonhosted.org/packages/d4/68/af23fbf90493044fc2ea83cd62923b9952c2d38eeeab83e0c016706bfbc8/cowsay-2.0.3-py2.py3-none-any.whl
Installing collected packages: cowsay
Successfully installed cowsay-2.0.3
pipx > (run_subprocess:112): running /home/markhyde/.local/pipx/venvs/cowsay/bin/python -c <contents of venv_metadata_inspector.py> cowsay /home/markhyde/.local/pipx/venvs/cowsay/bin
pipx > (_symlink_package_apps:108): ⚠️  Note: cowsay was already on your PATH at /usr/bin/cowsay
pipx > (needs_upgrade:51): Time since last upgrade of shared libs, in seconds: 5008.219198703766. Upgrade will be run by pipx if greater than 2592000.0.
  installed package cowsay 2.0.3, Python 3.8.3
  These apps are now globally available
    - cowsay
done! ✨ 🌟 ✨
```
So a reasonable workaround for me is to set `alias pipx='PIP_USER=0 pipx` in my .bashrc

**Comment by itsayellow** [comment]
Thanks for the helpful investigation @mark-hyde , and the extra ping on this issue.

I think we need to address this.  Using `--isolated` might be a blunt instrument, because it ignores all of the user's pip config.  There are some options that might be useful to get from the user's config, for example `proxy`.

Since I don't see a specific pip command-line option that only nullifies `--user`, the easiest course for pipx might be to inject `PIP_USER=0` into the env of the `pip install` command.
