### ISSUE TITLE
Packages don't uninstall properly on Windows

### ISSUE THREAD

**Issue by ofek** [pipxproject/pipx#120]
```
ofek.lev@ozone ~\Desktop $ dir /b C:\Users\ofek.lev\.local\bin
iptest.exe
iptest3.exe
ipython.exe
ipython3.exe
jupyter-bundlerextension.exe
jupyter-console.exe
jupyter-kernel.exe
jupyter-kernelspec.exe
jupyter-nbconvert.exe
jupyter-nbextension.exe
jupyter-notebook.exe
jupyter-qtconsole.exe
jupyter-run.exe
jupyter-serverextension.exe
jupyter-trust.exe
ofek.lev@ozone ~\Desktop $ pipx uninstall jupyter
Traceback (most recent call last):
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ofek.lev\Desktop\q\Miniconda3\Scripts\pipx.exe\__main__.py", line 9, in <module>
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\site-packages\pipx\main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\site-packages\pipx\main.py", line 189, in run_pipx_command
    commands.uninstall(venv_dir, package, LOCAL_BIN_DIR, verbose)
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\site-packages\pipx\commands.py", line 419, in uninstall
    file.unlink()
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\pathlib.py", line 1277, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\ofek.lev\\.local\\bin\\iptest.exe'
ofek.lev@ozone ~\Desktop $ pipx uninstall jupyter
Traceback (most recent call last):
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ofek.lev\Desktop\q\Miniconda3\Scripts\pipx.exe\__main__.py", line 9, in <module>
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\site-packages\pipx\main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\site-packages\pipx\main.py", line 189, in run_pipx_command
    commands.uninstall(venv_dir, package, LOCAL_BIN_DIR, verbose)
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\site-packages\pipx\commands.py", line 419, in uninstall
    file.unlink()
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\pathlib.py", line 1277, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\ofek.lev\\.local\\bin\\iptest3.exe'
ofek.lev@ozone ~\Desktop $ pipx uninstall jupyter
Traceback (most recent call last):
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ofek.lev\Desktop\q\Miniconda3\Scripts\pipx.exe\__main__.py", line 9, in <module>
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\site-packages\pipx\main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\site-packages\pipx\main.py", line 189, in run_pipx_command
    commands.uninstall(venv_dir, package, LOCAL_BIN_DIR, verbose)
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\site-packages\pipx\commands.py", line 419, in uninstall
    file.unlink()
  File "c:\users\ofek.lev\desktop\q\miniconda3\lib\pathlib.py", line 1277, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\ofek.lev\\.local\\bin\\ipython.exe'
ofek.lev@ozone ~\Desktop $ dir /b C:\Users\ofek.lev\.local\bin
ipython3.exe
jupyter-bundlerextension.exe
jupyter-console.exe
jupyter-kernel.exe
jupyter-kernelspec.exe
jupyter-nbconvert.exe
jupyter-nbextension.exe
jupyter-notebook.exe
jupyter-qtconsole.exe
jupyter-run.exe
jupyter-serverextension.exe
jupyter-trust.exe

```

**Comment by cs01** [comment]
If you have time to look into this and make a PR that would be much appreciated. Or maybe @sahensley could look into it?

**Comment by sahensley** [comment]
I'll see if I can make a Windows Nano Server Docker container to test this with and hopefully other Windows issues.  The container [here](https://github.com/LBates2000/python-windows) seems like a decent starting point.

**Comment by sahensley** [comment]
Thanks for the bug report!  I am closing this in favor of #210 where I've done some of the initial troubleshooting.
