### ISSUE TITLE
py -m pipx list does not work

### ISSUE THREAD

**Issue by pfmoore** [pipxproject/pipx#122]
I just tried pipx using Python 3.7.3 on Windows, which has just been released. I went through the following steps:

1. Uninstall Python 3.7.2, and install Python 3.7.3 (I didn't do an upgrade install).
2. `py -m pip install --user pipx` (note that I did *not* choose to add Python to my path when installing, that was deliberate).
3. `py -m pipx install invoke`
4. `py -m pipx list`

When I tried the list command I got the following traceback:

```
>py -m pipx list
venvs are in C:\Users\pfmoore\.local\pipx\venvs
binaries are exposed on your $PATH at C:\Users\pfmoore\.local\bin
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\pfmoore\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\pfmoore\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\pfmoore\AppData\Roaming\Python\Python37\site-packages\pipx\commands.py", line 525, in _get_package_summary
    metadata = venv.get_venv_metadata_for_package(package)
  File "C:\Users\pfmoore\AppData\Roaming\Python\Python37\site-packages\pipx\Venv.py", line 74, in get_venv_metadata_for_package
    stdout=subprocess.PIPE,
  File "C:\Users\pfmoore\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\pfmoore\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\pfmoore\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pfmoore\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pfmoore\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pfmoore\AppData\Roaming\Python\Python37\site-packages\pipx\__main__.py", line 5, in <module>
    cli()
  File "C:\Users\pfmoore\AppData\Roaming\Python\Python37\site-packages\pipx\main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "C:\Users\pfmoore\AppData\Roaming\Python\Python37\site-packages\pipx\main.py", line 187, in run_pipx_command
    commands.list_packages(PIPX_LOCAL_VENVS)
  File "C:\Users\pfmoore\AppData\Roaming\Python\Python37\site-packages\pipx\commands.py", line 586, in list_packages
    for package_summary in p.map(_get_package_summary, dirs):
  File "C:\Users\pfmoore\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\pfmoore\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by pfmoore** [comment]
Looks like this might be a Python bug - https://bugs.python.org/issue36435

**Comment by pfmoore** [comment]
No, it's not a Python bug - I messed up my minimal test case :-(

... and now I can't even reproduce the pipx issue locally :-(

I'm going to close this as not a bug, but it did happen that once, so maybe there's something in the traceback that points at an intermittent problem.  I'm OK with just classing it as user error though.
