### ISSUE TITLE
Problem with package with installed with "[all]"

### ISSUE THREAD

**Issue by jobevers** [pipxproject/pipx#180]
Python Language Server [suggests](https://github.com/palantir/python-language-server#installation) install with `pip install python-language-server[all]`.

I tried that and hit a snag:
```
» pipx install 'python-language-server[all]'                                                                                                     
Traceback (most recent call last):
  File "/home/jobevers/.local/pipx/venvs/python-language-server[all]/lib/python3.6/site-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
ModuleNotFoundError: No module named 'pip._vendor.requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/jobevers/.local/pipx/venvs/python-language-server[all]/lib/python3.6/site-packages/pip/__init__.py", line 24, in <module>
    from urllib3.exceptions import DependencyWarning
ModuleNotFoundError: No module named 'urllib3'
'/home/jobevers/.local/pipx/venvs/python-language-server[all]/bin/python -m pip install --upgrade pip -q' failed
```
Removing the `[all]` part:
```
» pipx install 'python-language-server'                                                                                                          
  installed package python-language-server 0.27.0, Python 3.6.8
  These binaries are now globally available
    - pyls
done! ✨ 🌟 ✨
```

Here is my version:
```
» pipx --version                                                                                                                               
0.12.3.0
```

**Comment by cs01** [comment]
It worked for me:
```
>> pipx install python-language-server[all]
  installed package 'python-language-server[all]' 0.27.0, Python 3.7.3
  These binaries are now globally available
    - pyls
done! ✨ 🌟 ✨
```

though I wouldn't recommend using a package name with the extras in it.

Regardless, these two options should work for you.

1. Install the extras by specifying the pip installation target separate (in `--spec`) from the name of the package
```
 pipx install python-language-server --spec python-language-server[all]
```

2. Install the standard package, then "inject" the extras
```
pipx install python-language-server
pipx inject python-language-server python-language-server[all]
```
I am going to close this issue since pipx has options to make this work. If you are still running into problems, feel free to re-open.
