### ISSUE TITLE
Pipx crashes during editable install

### ISSUE THREAD

**Issue by AliGhahraei** [pipxproject/pipx#378]
**Describe the bug**
Pipx 0.15.1.3 crashes during editable install.

**How to reproduce**

```bash
$ pipx install --verbose -e ~/g/scripts/maintenance
pipx > (run_subprocess:112): running /usr/bin/python -m venv --without-pip /tmp/tmpqvyi9c_8
pipx > (run_subprocess:112): running /tmp/tmpqvyi9c_8/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/ali/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /tmp/tmpqvyi9c_8/bin/python --version
pipx > (run_subprocess:112): running /tmp/tmpqvyi9c_8/bin/python -m pip list --format=json
pipx > (run_subprocess:112): running /tmp/tmpqvyi9c_8/bin/python -m pip install --no-dependencies --editable /home/ali/g/scripts/maintenance
Obtaining file:///home/ali/g/scripts/maintenance
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: maintenance
  Running setup.py develop for maintenance
Successfully installed maintenance
pipx > (run_subprocess:112): running /tmp/tmpqvyi9c_8/bin/python -m pip list --format=json
pipx > (install_package_no_deps:231): Determined package name: 'maintenance'
pipx > (_package_name_from_spec:104): Package name determined in 7.0s
pipx > (run_subprocess:112): running /usr/bin/python -m venv --without-pip /home/ali/.local/pipx/venvs/maintenance
pipx > (run_subprocess:112): running /home/ali/.local/pipx/venvs/maintenance/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/ali/.local/pipx/venvs/maintenance/bin/python --version
pipx > (run_subprocess:112): running /home/ali/.local/pipx/venvs/maintenance/bin/python -m pip install --editable /home/ali/g/scripts/maintenance
Obtaining file:///home/ali/g/scripts/maintenance
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Processing ./.cache/pip/wheels/ae/61/d2/51d0185d88a932058c7341ae08278b27f5312f3667efe433fc/colored-1.4.2-py3-none-any.whl
Collecting sh<2.0,>=1.12
  Using cached sh-1.12.14-py2.py3-none-any.whl (38 kB)
Installing collected packages: colored, sh, maintenance
  Running setup.py develop for maintenance
Successfully installed colored-1.4.2 maintenance sh-1.12.14
pipx > (run_subprocess:112): running /home/ali/.local/pipx/venvs/maintenance/bin/python -c #!/usr/bin/env python3

import json
import sys
from pathlib import Path
from typing import Dict, List, Optional


try:
    WindowsError
except NameError:
    WINDOWS = False
else:
    WINDOWS = True


def get_package_dependencies(package: str) -> List[str]:
    try:
        import pkg_resources
    except Exception:
        return []
    return [str(r) for r in pkg_resources.get_distribution(package).requires()]


def get_package_version(package: str) -> Optional[str]:
    try:
        import pkg_resources

        return pkg_resources.get_distribution(package).version
    except Exception:
        return None


def get_apps(package: str, bin_path: Path) -> List[str]:
    try:
        import pkg_resources
    except Exception:
        return []
    dist = pkg_resources.get_distribution(package)

    apps = set()
    for section in ["console_scripts", "gui_scripts"]:
        # "entry_points" entry in setup.py are found here
        for name in pkg_resources.get_entry_map(dist).get(section, []):
            if (bin_path / name).exists():
                apps.add(name)
            if WINDOWS and (bin_path / (name + ".exe")).exists():
                # WINDOWS adds .exe to entry_point name
                apps.add(name + ".exe")

    if dist.has_metadata("RECORD"):
        # for non-editable package installs, RECORD is list of installed files
        # "scripts" entry in setup.py is found here (test w/ awscli)
        for line in dist.get_metadata_lines("RECORD"):
            entry = line.split(",")[0]  # noqa: T484
            path = (Path(dist.location) / entry).resolve()
            try:
                if path.parent.samefile(bin_path):
                    apps.add(Path(entry).name)
            except FileNotFoundError:
                pass

    if dist.has_metadata("installed-files.txt"):
        # not sure what is found here
        for line in dist.get_metadata_lines("installed-files.txt"):
            entry = line.split(",")[0]  # noqa: T484
            path = (Path(dist.egg_info) / entry).resolve()  # type: ignore
            try:
                if path.parent.samefile(bin_path):
                    apps.add(Path(entry).name)
            except FileNotFoundError:
                pass

    return sorted(apps)


def _dfs_package_apps(
    bin_path: Path,
    package: str,
    app_paths_of_dependencies: Dict[str, List[Path]],
    dep_visited: Optional[Dict[str, bool]] = None,
) -> Dict[str, List[Path]]:
    if dep_visited is None:
        dep_visited = {}

    dependencies = get_package_dependencies(package)
    for d in dependencies:
        app_names = get_apps(d, bin_path)
        if app_names:
            app_paths_of_dependencies[d] = [bin_path / app for app in app_names]
        # recursively search for more
        if d not in dep_visited:
            # only search if this package isn't already listed to avoid
            # infinite recursion
            dep_visited[d] = True
            app_paths_of_dependencies = _dfs_package_apps(
                bin_path, d, app_paths_of_dependencies, dep_visited
            )
    return app_paths_of_dependencies


def _windows_extra_app_paths(app_paths: List[Path]) -> List[Path]:
    # In Windows, editable package have additional files starting with the
    #   same name that are required to be in the same dir to run the app
    # Add "*-script.py", "*.exe.manifest" only to app_paths to make
    #   execution work; do not add them to apps to ensure they are not listed
    app_paths_output = app_paths.copy()
    for app_path in app_paths:
        win_app_path = app_path.parent / (app_path.stem + "-script.py")
        if win_app_path.exists():
            app_paths_output.append(win_app_path)
        win_app_path = app_path.parent / (app_path.stem + ".exe.manifest")
        if win_app_path.exists():
            app_paths_output.append(win_app_path)
    return app_paths_output


def main():
    package = sys.argv[1]
    bin_path = Path(sys.argv[2])

    apps = get_apps(package, bin_path)
    app_paths = [Path(bin_path) / app for app in apps]
    if WINDOWS:
        app_paths = _windows_extra_app_paths(app_paths)
    app_paths = [str(app_path) for app_path in app_paths]

    app_paths_of_dependencies = {}  # type: Dict[str, List[str]]
    apps_of_dependencies = []  # type: List[str]
    app_paths_of_dependencies = _dfs_package_apps(
        bin_path, package, app_paths_of_dependencies
    )
    for dep in app_paths_of_dependencies:
        apps_of_dependencies += [
            dep_path.name for dep_path in app_paths_of_dependencies[dep]
        ]
        if WINDOWS:
            app_paths_of_dependencies[dep] = _windows_extra_app_paths(
                app_paths_of_dependencies[dep]
            )
        app_paths_of_dependencies[dep] = [
            str(dep_path) for dep_path in app_paths_of_dependencies[dep]
        ]

    output = {
        "apps": apps,
        "app_paths": app_paths,
        "apps_of_dependencies": apps_of_dependencies,
        "app_paths_of_dependencies": app_paths_of_dependencies,
        "package_version": get_package_version(package),
        "python_version": "Python {}.{}.{}".format(
            sys.version_info.major, sys.version_info.minor, sys.version_info.micro
        ),
    }

    print(json.dumps(output))


if __name__ == "__main__":
    try:
        main()
    except Exception:
        print(
            json.dumps(
                {
                    "apps": [],
                    "app_paths": [],
                    "app_paths_of_dependencies": {},
                    "package_version": None,
                    "python_version": None,
                }
            )
        )
 maintenance /home/ali/.local/pipx/venvs/maintenance/bin

pipx > (rmdir:18): removing directory /home/ali/.local/pipx/venvs/maintenance
Traceback (most recent call last):
  File "/usr/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.15.1.3', 'console_scripts', 'pipx')()
  File "/usr/lib/python3.8/site-packages/pipx/main.py", line 590, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/usr/lib/python3.8/site-packages/pipx/main.py", line 162, in run_pipx_command
    return commands.install(
  File "/usr/lib/python3.8/site-packages/pipx/commands/commands.py", line 63, in install
    venv.install_package(
  File "/usr/lib/python3.8/site-packages/pipx/venv.py", line 195, in install_package
    self._update_package_metadata(
  File "/usr/lib/python3.8/site-packages/pipx/venv.py", line 265, in _update_package_metadata
    venv_package_metadata = self.get_venv_metadata_for_package(package)
  File "/usr/lib/python3.8/site-packages/pipx/venv.py", line 254, in get_venv_metadata_for_package
    return VenvMetadata(**data)
TypeError: __new__() missing 1 required positional argument: 'apps_of_dependencies'
```

**Expected behavior**
The package should have been installed.

Thank you for the help!

**Comment by itsayellow** [comment]
One thing is that our exception handling in `venv_metadata_inspector.py` isn't returning a proper dict full of empty data...it needs another key `apps_of_dependencies`.

Unfortunately it also appears that because we are catching the Exception and not printing it, I can't tell what went wrong inside of `venv_metadata_inspector.py`.  Shouldn't we at least print the stack trace in verbose mode so we know what happened?

**Comment by itsayellow** [comment]
@AliGhahraei , is your `maintenance` available for us to try out, perhaps in a publicly-accessible git repo somewhere?  Unfortunately I don't think we can debug from your posted output, due to the limited output that `pipx` is providing us.

**Comment by AliGhahraei** [comment]
@itsayellow sorry for taking so long to respond. I do have a [public repo](https://github.com/AliGhahraei/scripts/tree/master/maintenance), but unfortunately I'm no longer able to reproduce the issue. I just tried today and it worked:

```
$ pipx install --verbose -e ~/g/scripts/maintenance
pipx > (run_subprocess:112): running /usr/bin/python -m venv --without-pip /tmp/tmpz2s6q1vn
pipx > (run_subprocess:112): running /tmp/tmpz2s6q1vn/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/ali/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /tmp/tmpz2s6q1vn/bin/python --version
pipx > (run_subprocess:112): running /tmp/tmpz2s6q1vn/bin/python -m pip list --format=json
pipx > (run_subprocess:112): running /tmp/tmpz2s6q1vn/bin/python -m pip install --no-dependencies --editable /home/ali/g/scripts/maintenance
Obtaining file:///home/ali/g/scripts/maintenance
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: maintenance
  Running setup.py develop for maintenance
Successfully installed maintenance
pipx > (run_subprocess:112): running /tmp/tmpz2s6q1vn/bin/python -m pip list --format=json
pipx > (install_package_no_deps:231): Determined package name: 'maintenance'
pipx > (_package_name_from_spec:104): Package name determined in 8.4s
pipx > (run_subprocess:112): running /usr/bin/python -m venv --without-pip /home/ali/.local/pipx/venvs/maintenance
pipx > (run_subprocess:112): running /home/ali/.local/pipx/venvs/maintenance/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/ali/.local/pipx/venvs/maintenance/bin/python --version
pipx > (run_subprocess:112): running /home/ali/.local/pipx/venvs/maintenance/bin/python -m pip install --editable /home/ali/g/scripts/maintenance
Obtaining file:///home/ali/g/scripts/maintenance
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Processing ./.cache/pip/wheels/ae/61/d2/51d0185d88a932058c7341ae08278b27f5312f3667efe433fc/colored-1.4.2-py3-none-any.whl
Collecting sh<2.0,>=1.12
  Downloading sh-1.13.1-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 590 kB/s 
Installing collected packages: colored, sh, maintenance
  Running setup.py develop for maintenance
Successfully installed colored-1.4.2 maintenance sh-1.13.1
pipx > (run_subprocess:112): running /home/ali/.local/pipx/venvs/maintenance/bin/python -c #!/usr/bin/env python3

import json
import sys
from pathlib import Path
from typing import Dict, List, Optional


try:
    WindowsError
except NameError:
    WINDOWS = False
else:
    WINDOWS = True


def get_package_dependencies(package: str) -> List[str]:
    try:
        import pkg_resources
    except Exception:
        return []
    return [str(r) for r in pkg_resources.get_distribution(package).requires()]


def get_package_version(package: str) -> Optional[str]:
    try:
        import pkg_resources

        return pkg_resources.get_distribution(package).version
    except Exception:
        return None


def get_apps(package: str, bin_path: Path) -> List[str]:
    try:
        import pkg_resources
    except Exception:
        return []
    dist = pkg_resources.get_distribution(package)

    apps = set()
    for section in ["console_scripts", "gui_scripts"]:
        # "entry_points" entry in setup.py are found here
        for name in pkg_resources.get_entry_map(dist).get(section, []):
            if (bin_path / name).exists():
                apps.add(name)
            if WINDOWS and (bin_path / (name + ".exe")).exists():
                # WINDOWS adds .exe to entry_point name
                apps.add(name + ".exe")

    if dist.has_metadata("RECORD"):
        # for non-editable package installs, RECORD is list of installed files
        # "scripts" entry in setup.py is found here (test w/ awscli)
        for line in dist.get_metadata_lines("RECORD"):
            entry = line.split(",")[0]  # noqa: T484
            path = (Path(dist.location) / entry).resolve()
            try:
                if path.parent.samefile(bin_path):
                    apps.add(Path(entry).name)
            except FileNotFoundError:
                pass

    if dist.has_metadata("installed-files.txt"):
        # not sure what is found here
        for line in dist.get_metadata_lines("installed-files.txt"):
            entry = line.split(",")[0]  # noqa: T484
            path = (Path(dist.egg_info) / entry).resolve()  # type: ignore
            try:
                if path.parent.samefile(bin_path):
                    apps.add(Path(entry).name)
            except FileNotFoundError:
                pass

    return sorted(apps)


def _dfs_package_apps(
    bin_path: Path,
    package: str,
    app_paths_of_dependencies: Dict[str, List[Path]],
    dep_visited: Optional[Dict[str, bool]] = None,
) -> Dict[str, List[Path]]:
    if dep_visited is None:
        dep_visited = {}

    dependencies = get_package_dependencies(package)
    for d in dependencies:
        app_names = get_apps(d, bin_path)
        if app_names:
            app_paths_of_dependencies[d] = [bin_path / app for app in app_names]
        # recursively search for more
        if d not in dep_visited:
            # only search if this package isn't already listed to avoid
            # infinite recursion
            dep_visited[d] = True
            app_paths_of_dependencies = _dfs_package_apps(
                bin_path, d, app_paths_of_dependencies, dep_visited
            )
    return app_paths_of_dependencies


def _windows_extra_app_paths(app_paths: List[Path]) -> List[Path]:
    # In Windows, editable package have additional files starting with the
    #   same name that are required to be in the same dir to run the app
    # Add "*-script.py", "*.exe.manifest" only to app_paths to make
    #   execution work; do not add them to apps to ensure they are not listed
    app_paths_output = app_paths.copy()
    for app_path in app_paths:
        win_app_path = app_path.parent / (app_path.stem + "-script.py")
        if win_app_path.exists():
            app_paths_output.append(win_app_path)
        win_app_path = app_path.parent / (app_path.stem + ".exe.manifest")
        if win_app_path.exists():
            app_paths_output.append(win_app_path)
    return app_paths_output


def main():
    package = sys.argv[1]
    bin_path = Path(sys.argv[2])

    apps = get_apps(package, bin_path)
    app_paths = [Path(bin_path) / app for app in apps]
    if WINDOWS:
        app_paths = _windows_extra_app_paths(app_paths)
    app_paths = [str(app_path) for app_path in app_paths]

    app_paths_of_dependencies = {}  # type: Dict[str, List[str]]
    apps_of_dependencies = []  # type: List[str]
    app_paths_of_dependencies = _dfs_package_apps(
        bin_path, package, app_paths_of_dependencies
    )
    for dep in app_paths_of_dependencies:
        apps_of_dependencies += [
            dep_path.name for dep_path in app_paths_of_dependencies[dep]
        ]
        if WINDOWS:
            app_paths_of_dependencies[dep] = _windows_extra_app_paths(
                app_paths_of_dependencies[dep]
            )
        app_paths_of_dependencies[dep] = [
            str(dep_path) for dep_path in app_paths_of_dependencies[dep]
        ]

    output = {
        "apps": apps,
        "app_paths": app_paths,
        "apps_of_dependencies": apps_of_dependencies,
        "app_paths_of_dependencies": app_paths_of_dependencies,
        "package_version": get_package_version(package),
        "python_version": "Python {}.{}.{}".format(
            sys.version_info.major, sys.version_info.minor, sys.version_info.micro
        ),
    }

    print(json.dumps(output))


if __name__ == "__main__":
    try:
        main()
    except Exception:
        print(
            json.dumps(
                {
                    "apps": [],
                    "app_paths": [],
                    "app_paths_of_dependencies": {},
                    "package_version": None,
                    "python_version": None,
                }
            )
        )
 maintenance /home/ali/.local/pipx/venvs/maintenance/bin
pipx > (needs_upgrade:51): Time since last upgrade of shared libs, in seconds: 1048557.8911406994. Upgrade will be run by pipx if greater than 2592000.0.
  installed package maintenance 0.1.0, Python 3.8.2
  These apps are now globally available
    - nix_maintenance
done! ✨ 🌟 ✨
```

I'll close this now. Thanks!
