### ISSUE TITLE
crash when running pipx install on Windows

### ISSUE THREAD

**Issue by hwmrocker** [pipxproject/pipx#412]
**Describe the bug**

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\pipx.exe\__main__.py", line 9, in <module>
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipx\main.py", line 
580, in cli
    return run_pipx_command(parsed_pipx_args)
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipx\main.py", line 
151, in run_pipx_command
    return commands.install(
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipx\commands\instal    run_post_install_actions(
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipx\commands\common.py", line 293, in run_post_install_actions
    print(get_package_summary(venv_dir, package=package, new_install=True))
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipx\commands\common.py", line 131, in get_package_summary
.py", line 172, in _get_exposed_app_paths_for_package
    if is_same_file:
UnboundLocalError: local variable 'is_same_file' referenced before assignment
```

```
PS C:\Users\micro> pipx --version
0.15.3.1
PS C:\Users\micro> python --version
Python 3.8.3
PS C:\Users\micro>
```
**How to reproduce**
pipx list
pipx install pyugrade

**Expected behavior**
No exception should be raised.

**Comment by cs01** [comment]
Thanks for reporting. I'll put a fix in soon.

**Comment by cs01** [comment]
@hwmrocker  would you be able to test out https://github.com/pipxproject/pipx/pull/413 and confirm it fixes the issue?

**Comment by hwmrocker** [comment]
wow this was fast, just wanted to create a PR.
I will test this, in the afternoon, when I boot windows again.

**Comment by hwmrocker** [comment]
Thank you very much, this issue is now fixed :)
