### ISSUE TITLE
pipx upgrade poetry fails

### ISSUE THREAD

**Issue by spleiner** [pipxproject/pipx#420]
**Describe the bug**
Whenever I try to upgrade poetry (previously successfully installed by `pipx install poetry`) I get an error.

**How to reproduce**
Run `pipx upgrade poetry`

**Expected behavior**
poetry version successfully upgraded

**Output**
```
$ pipx upgrade poetry                                                                                                                                                        

ERROR: Command errored out with exit status 1:neDrive - SEB\\Dev\\poetry'                                                                                                  
   command: 'C:\Users\UserX\.local\pipx\venvs\poetry\Scripts\python.exe' 'C:\Users\UserX\.local\pipx\shared\Lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\UserX\AppData\Local\Temp\tmp5163i0hj'                                                                                                          
       cwd: C:\Users\UserX\AppData\Local\Temp\pip-req-build-6j300oyo                                                                                                        
  Complete output (36 lines):                                                                                                                                                
  Traceback (most recent call last):                                                                                                                                         
    File "C:\Users\UserX\.local\pipx\shared\Lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>                                                     
      main()                                                                                                                                                                 
    File "C:\Users\UserX\.local\pipx\shared\Lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main                                                         
      json_out['return_val'] = hook(**hook_input['kwargs'])                                                                                                                  
    File "C:\Users\UserX\.local\pipx\shared\Lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel                                 
      return hook(config_settings)                                                                                                                                           
    File "C:\Users\UserX\AppData\Local\Temp\pip-build-env-uyrdfq01\overlay\Lib\site-packages\intreehooks.py", line 53, in get_requires_for_build_wheel                      
      return self._backend.get_requires_for_build_sdist(config_settings)                                                                                                     
    File "C:\Users\UserX\AppData\Local\Temp\pip-build-env-uyrdfq01\overlay\Lib\site-packages\intreehooks.py", line 38, in _backend                                          
      obj = self._module_from_dir(modname)                                                                                                                                   
    File "C:\Users\UserX\AppData\Local\Temp\pip-build-env-uyrdfq01\overlay\Lib\site-packages\intreehooks.py", line 25, in _module_from_dir                                  
      mod = importlib.import_module(modname)                                                                                                                                 
    File "c:\users\UserX\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module                                                      
      return _bootstrap._gcd_import(name[level:], package, level)                                                                                                            
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                                          
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                        
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked                                                                                               
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                             
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                                          
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                        
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                               
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                                        
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                                                                  
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                             
    File "C:\Users\UserX\AppData\Local\Temp\pip-req-build-6j300oyo\poetry\masonry\__init__.py", line 10, in <module>                                                        
      from .builder import Builder                                                                                                                                           
    File "C:\Users\UserX\AppData\Local\Temp\pip-req-build-6j300oyo\poetry\masonry\builder.py", line 1, in <module>                                                          
      from .builders.complete import CompleteBuilder                                                                                                                         
    File "C:\Users\UserX\AppData\Local\Temp\pip-req-build-6j300oyo\poetry\masonry\builders\__init__.py", line 1, in <module>                                                
      from .complete import CompleteBuilder                                                                                                                                  
    File "C:\Users\UserX\AppData\Local\Temp\pip-req-build-6j300oyo\poetry\masonry\builders\complete.py", line 6, in <module>                                                
      from poetry.factory import Factory                                                                                                                                     
    File "C:\Users\UserX\AppData\Local\Temp\pip-req-build-6j300oyo\poetry\factory.py", line 10, in <module>                                                                 
      from clikit.api.io.io import IO                                                                                                                                        
  ModuleNotFoundError: No module named 'clikit'                                                                                                                              
  ----------------------------------------                                                                                                                                   
ERROR: Command errored out with exit status 1: 'C:\Users\UserX\.local\pipx\venvs\poetry\Scripts\python.exe' 'C:\Users\UserX\.local\pipx\shared\Lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\UserX\AppData\Local\Temp\tmp5163i0hj' Check the logs for full command output.                               
'C:\\Users\\UserX\\.local\\pipx\\venvs\\poetry\\Scripts\\python.exe -m pip install --upgrade C:\\Users\\UserX\\OneDrive - Work\\Dev\\poetry -q' failed   
```

**Comment by itsayellow** [comment]
The poetry bug was fixed.
