### ISSUE TITLE
Error when trying to install a package

### ISSUE THREAD

**Issue by obayit** [pipxproject/pipx#580]
**Describe the bug**

When trying to install a package it gives an error, for example the output of `pipx install --verbose copier` is:

```
pipx > (setup:567): pipx version is 0.15.6.0
pipx > (setup:568): Default python interpreter is '/usr/bin/python3'
pipx > (package_name_from_spec:247): Determined package name: copier
pipx > (package_name_from_spec:248): Package name determined in 0.0s
creating virtual environment...
pipx > (run_subprocess:113): running /usr/bin/python3 -m venv --without-pip /home/obi/.local/pipx/venvs/copier
pipx > (run_subprocess:113): running /home/obi/.local/pipx/venvs/copier/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:113): running /home/obi/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:113): running /home/obi/.local/pipx/venvs/copier/bin/python --version
pipx > (_parsed_package_to_package_or_url:127): cleaned package spec: copier
installing copier...
pipx > (run_subprocess:113): running /home/obi/.local/pipx/venvs/copier/bin/python -m pip install copier
Traceback (most recent call last):
  File "/home/obi/.local/pipx/shared/lib/python3.6/site-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
ModuleNotFoundError: No module named 'pip._vendor.requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/obi/.local/pipx/shared/lib/python3.6/site-packages/pip/__init__.py", line 24, in <module>
    from urllib3.exceptions import DependencyWarning
ModuleNotFoundError: No module named 'urllib3'
pipx > (install_package:203): '/home/obi/.local/pipx/venvs/copier/bin/python -m pip install copier' failed

pipx > (rmdir:17): removing directory /home/obi/.local/pipx/venvs/copier
Error installing copier.
```
**How to reproduce**

I am not sure, but, I installed pipx with python2 at first by mistake then removed it, and installed the python3 version after that. (because the default python version in Ubuntu 18.04 is 2 not 3)
FYI it works on the same machine with a different user!

OS: Ubuntu 18.04

**Comment by itsayellow** [comment]
It might be easiest if you just started over with this user's local pipx data directory.  I'm assuming you haven't successfully installed anything yet with pipx for this user so you shouldn't be losing anything.

Try:
```
rm -rf ~/.local/pipx
```
and then try `pipx install --verbose copier` again.

(Advanced note: It looks to me like your pipx shared packages' venv is not right, which is `~/.local/pipx/shared`)

**Comment by obayit** [comment]
Worked like a charm, thanks.
