### ISSUE TITLE
Packages with . in their name are no longer install-able - Internal Error

### ISSUE THREAD

**Issue by gaborbernat** [pipxproject/pipx#587]
This worked a few months ago, but now it fails. For example:

```
pipx install kreagroup.jsi18n                                                                                                                                                                    Internal error with venv metadata inspection.

Unable to install kreagroup-jsi18n.
Check the name or spec for errors, and verify that it can be installed with pip.
```

@itsayellow any ideas about why this could be?

**Comment by itsayellow** [comment]
I get a slightly different error with:
```
> pipx install kreagroup.jsi18n
Internal error with venv metadata inspection.

Unable to install kreagroup-jsi18n.
Check the name or spec for errors, and verify that it can be installed with pip.
>
```
When I try with --verbose it appears that `venv_metadata_inspector.py` can't find a matching distribution for `kreagroup-jsi18n`.  It should work, we try to normalize both the input name and each distribution name to find a match.  Let me do some debugging and see what's happening.

**Comment by itsayellow** [comment]
One thing I notice from using `pip` to install it, is that `kreagroup.jsi18n` has no apps.

So it should fail but with a different and more informative error.

**Comment by itsayellow** [comment]
```shell
> pipx install kreagroup.jsi18n --verbose
pipx > (setup:567): pipx version is 0.15.6.0
pipx > (setup:568): Default python interpreter is '/usr/local/opt/python@3.9/bin/python3.9'
pipx > (package_name_from_spec:247): Determined package name: kreagroup-jsi18n
pipx > (package_name_from_spec:248): Package name determined in 0.0s
creating virtual environment...
pipx > (run_subprocess:113): running /usr/local/opt/python@3.9/bin/python3.9 -m venv --without-pip /Users/mclapp/.local/pipx/venvs/kreagroup-jsi18n
pipx > (run_subprocess:113): running /Users/mclapp/.local/pipx/venvs/kreagroup-jsi18n/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:113): running /Users/mclapp/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:113): running /Users/mclapp/.local/pipx/venvs/kreagroup-jsi18n/bin/python --version
pipx > (_parsed_package_to_package_or_url:127): cleaned package spec: kreagroup-jsi18n
installing kreagroup-jsi18n...
pipx > (run_subprocess:113): running /Users/mclapp/.local/pipx/venvs/kreagroup-jsi18n/bin/python -m pip install kreagroup-jsi18n
Collecting kreagroup-jsi18n
  Using cached kreagroup.jsi18n-1.0.3-py3-none-any.whl
Requirement already satisfied: setuptools in /Users/mclapp/.local/pipx/shared/lib/python3.9/site-packages (from kreagroup-jsi18n) (50.3.2)
Collecting jarn.jsi18n==1.0
  Using cached jarn.jsi18n-1.0-py3-none-any.whl
Requirement already satisfied: setuptools in /Users/mclapp/.local/pipx/shared/lib/python3.9/site-packages (from kreagroup-jsi18n) (50.3.2)
Installing collected packages: jarn.jsi18n, kreagroup-jsi18n
Successfully installed jarn.jsi18n-1.0 kreagroup-jsi18n
pipx > (run_subprocess:113): running /Users/mclapp/.local/pipx/venvs/kreagroup-jsi18n/bin/python -c <contents of venv_metadata_inspector.py> kreagroup-jsi18n /Users/mclapp/.local/pipx/venvs/kreagroup-jsi18n/bin
pipx > (get_venv_metadata_for_package:282): Internal error with venv metadata inspection.
pipx > (get_venv_metadata_for_package:283): venv_metadata_inspector.py Traceback:
Traceback (most recent call last):
  File "<string>", line 159, in <module>
  File "<string>", line 120, in main
  File "<string>", line 37, in get_apps
  File "/Users/mclapp/.local/pipx/shared/lib/python3.9/site-packages/pkg_resources/__init__.py", line 465, in get_distribution
    dist = get_provider(dist)
  File "/Users/mclapp/.local/pipx/shared/lib/python3.9/site-packages/pkg_resources/__init__.py", line 341, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/mclapp/.local/pipx/shared/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/mclapp/.local/pipx/shared/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'kreagroup-jsi18n' distribution was not found and is required by the application
pipx > (_parsed_package_to_package_or_url:127): cleaned package spec: kreagroup-jsi18n

pipx > (rmdir:17): removing directory /Users/mclapp/.local/pipx/venvs/kreagroup-jsi18n
Unable to install kreagroup-jsi18n.
Check the name or spec for errors, and verify that it can be installed with pip.
>
```

**Comment by itsayellow** [comment]
We are giving the canonicalized name `kreagroup-jsi18n` to `dist = pkg_resources.get_distribution(package)` and `get_distribution` can't find it.

**Comment by gaborbernat** [comment]
Yeah, I know this one has no app, but it's because I could not find an example that has. However, I have some private packages I can't publish that do have apps (but can't publish it, sadly the code for them) and throws this code. So it's a way to reproduce it, though yeah, this example should fail.

**Comment by itsayellow** [comment]
OK I guess this is the same as bug #528 .

I thought `venv_metadata_inspector.py` was properly handling canonicalized names, but apparently not yet.  I guess this just means I have to get my PR submitted with the update to `venv_metadata_inspector.py`.

**Comment by diazona** [comment]
If there's still a concern about having a good example to reproduce the issue, feel free to take anything useful from https://github.com/diazona/pipx-bug-test-project.

**Comment by itsayellow** [comment]
#593 will be landing soon, and should take care of this.
