### ISSUE TITLE
Problem when install from git branch + poetry

### ISSUE THREAD

**Issue by pmav99** [pipxproject/pipx#59]
When I try to install from a git branch of a project which uses `poetry` (i.e. no setuptools), pipx chokes because there is no `setup.py`. E.g. This is the traceback for installing the `develop` branch of [poetry](https://github.com/sdispater/poetry) itself
```
pipx install --spec 'git+https://github.com/sdispater/poetry.git@develop' poetry --verbose
pipx (run_pipx_command:626): virtualenv location is /home/feanor/.local/pipx/venvs/poetry
pipx (_run:230): running /usr/bin/python -m venv /home/feanor/.local/pipx/venvs/poetry
pipx (_run:230): running /home/feanor/.local/pipx/venvs/poetry/bin/python -m pip install --upgrade pip
Looking in links: /home/feanor/.wheelhouse
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.1
pipx (_run:230): running /home/feanor/.local/pipx/venvs/poetry/bin/python -m pip install git+https://github.com/sdispater/poetry.git@develop#egg=poetry
Looking in links: /home/feanor/.wheelhouse
Collecting poetry from git+https://github.com/sdispater/poetry.git@develop#egg=poetry
  Cloning https://github.com/sdispater/poetry.git (to revision develop) to ./feanor/pip-install-xsy609ai/poetry
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/feanor/pip-install-xsy609ai/poetry/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/feanor/pip-install-xsy609ai/poetry/
pipx (rmdir:240): removing directory /home/feanor/.local/pipx/venvs/poetry
'/home/feanor/.local/pipx/venvs/poetry/bin/python -m pip install git+https://github.com/sdispater/poetry.git@develop#egg=poetry' failed
```
I am not sure if this is something under the scope of pipx, but at the very least handling the exception and giving a message should be better from a UX point of view.

**Comment by cs01** [comment]
Pip itself will be adding support for this. See https://github.com/pypa/pip/issues/5407.

**Comment by xsteadfastx** [comment]
it works for me. i use for example this:

`pipx install --verbose --spec git+https://github.com/xsteadfastx/flickr2pelican.git flickr2pelican`

**Comment by cs01** [comment]
Ironically, poetry's `pyproject.toml` does not have the required entry in it to make it compatible with pip.

```
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

flickr2pelican does, and therefore it works with pipx. You should file an issue/pull request with the poetry project to resolve this.

Compare the pyproject.toml files:
https://github.com/sdispater/poetry/blob/df59c3d40703c8467d73f57ac72cf35bd3747dad/pyproject.toml

https://github.com/xsteadfastx/flickr2pelican/blob/a412e3d959929c8aa4b2175d0dae0b159011e14c/pyproject.toml#L30
