### ISSUE TITLE
pipx does not use pip args when upgrading shared libraries?

### ISSUE THREAD

**Issue by pawamoy** [pipxproject/pipx#604]
**Describe the bug**
It seems pipx is not using the options I specify with `--pip-args` when upgrading or creating the shared libraries.

**How to reproduce**
Pass a custom index url, certificate path, or trusted host in `--pip-args`, and run `pipx install --verbose my-package`.

Here is the output with `set -x` (Bash):

```
+ pipx install --verbose '--pip-args=--disable-pip-version-check --index-url https://redacted.com/simple/ --cert ca-bundle.crt --trusted-host redacted.com' my-package
pipx >(setup:704): pipx version is 0.16.0.0
pipx >(setup:705): Default python interpreter is '/home/jboss/bin/python'
pipx >(package_name_from_spec:299): Determined package name: my-package
pipx >(package_name_from_spec:300): Package name determined in 0.0s
pipx >(run_subprocess:120): running /home/jboss/bin/python -m venv --without-pip /home/jboss/.local/pipx/venvs/my-package
pipx >(run_subprocess:120): running /home/jboss/bin/python -m venv --clear /home/jboss/.local/pipx/shared
pipx >(upgrade:84): Upgrading shared libraries in /home/jboss/.local/pipx/shared
pipx >(run_subprocess:120): running /home/jboss/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install --force-reinstall --upgrade pip setuptools wheel
```

At this point, it hangs a bit (requests retries), and fail for various reasons, simply because the given options are not used. For example, SSL errors:

```
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),)': /simple/pip/
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip
pipx >(upgrade:112): Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/home/jboss/.local/lib/python3.6/site-packages/pipx/shared_libs.py", line 106, in upgrade
    subprocess_post_check(upgrade_process)
  File "/home/jboss/.local/lib/python3.6/site-packages/pipx/util.py", line 151, in subprocess_post_check
    f"{' '.join([str(x) for x in completed_process.args])!r} failed"
pipx.util.PipxError: '/home/jboss/.local/pipx/shared/bin/python -m pip --disable-pip-version-check
install --force-reinstall --upgrade pip setuptools wheel' failed
```

Then it resumes the package installation:

```
pipx >(run_subprocess:120): running /home/jboss/.local/pipx/venvs/my-package/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:120): running /home/jboss/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:120): running /home/jboss/.local/pipx/venvs/my-package/bin/python --version
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: my-package
pipx >(run_subprocess:120): running /home/jboss/.local/pipx/venvs/my-package/bin/python -m pip install --disable-pip-version-check --index-url https://redacted.com/simple/ --cert ca-bundle.crt --trusted-host redacted.com my-package
```

...and hangs again, this time I don't know why, since the pip args are used. Maybe because the shared libraries were not upgraded correctly? I'll continue the investigation on this point.
UPDATE: it hangs when running Black's `setup.py` (Black is one of my-package's dependencies), so pipx is working fine here. Must be my Docker base image that has difficulties building Black ^^'
UPDATE: pip and setuptools needed to be updated, and wheel installed for black to install correctly!

**Expected behavior**
Shouldn't pipx use the pip args while creating/upgrading the shared libraries as well?

**Comment by pawamoy** [comment]
Alternative solutions:

- using pip environment variables:
  ```bash
  export PIP_INDEX_URL="https://redacted.com/simple/"
  export PIP_CERT="ca-bundle.crt"
  export PIP_TRUSTED_HOST="redacted.com"
  ```
- using pip configuration file in ~/.config/pip/pip.conf:
  ```
  [global]
  trusted-host = redacted.com
  index-url = https://redacted.com/simple/
  cert = /home/user/certs/ca-bundle.crt
  ```

This will make pip use these options even if pipx does not pass them to pip.

**Comment by itsayellow** [comment]
This was actually a question during a recent code update, because there are many commands that can trigger an update in the shared libraries, and only some of them receive `pip_args`.  It was thought that rather than apply pip arguments sporadically and inconsistently, we should just not apply them to the shared libraries during a pipx command and instead rely on users to use the workarounds you list above.

https://github.com/pipxproject/pipx/issues/544

**Comment by itsayellow** [comment]
I'm going to close this in favor or #609 .  Please comment there if you have additional comments.  Thanks for bringing this to our attention.
