### ISSUE TITLE
Failure to install -e .

### ISSUE THREAD

**Issue by danielhoherd** [pipxproject/pipx#85]
When running `pipx install -e .` I see an error. However, if I cd one level up and run `pipx install -e package_name` it works fine.

```
$ pipx --version
0.12.0.0
$ git clone git@github.com:danielhoherd/plexdl.git
Cloning into 'plexdl'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 185 (delta 34), reused 63 (delta 15), pack-reused 99
Receiving objects: 100% (185/185), 30.46 KiB | 725.00 KiB/s, done.
Resolving deltas: 100% (89/89), done.
$ cd plexdl/
/Users/daniel.hoherd/temp/2019-02-06/plexdl
$ git rev-parse HEAD
925b0bcdbbb58240555b4470037ed8cef44100b2
$ pipx install -e .
Traceback (most recent call last):
  File "/Users/daniel.hoherd/Library/Python/3.7/bin/pipx", line 10, in <module>
    sys.exit(cli())
  File "/Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/pipx/main.py", line 923, in cli
    exit(run_pipx_command(args))
  File "/Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/pipx/main.py", line 661, in run_pipx_command
    force=args.force,
  File "/Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/pipx/main.py", line 464, in install
    if venv_dir.exists() and next(venv_dir.iterdir()):
StopIteration
$ cd ..
$ pipx install -e plexdl
  installed package plexdl 0.1.0, Python 3.7.2
  These binaries are now globally available
    - plexdl
done! ✨ 🌟 ✨
```

**Comment by cs01** [comment]
I think you need to do

```
pipx install -e plexdl --spec .
```

Let me know if that's the case and I can find somewhere to document that.

**Comment by danielhoherd** [comment]
My bad. I read [this part of the docs](https://github.com/pipxproject/pipx#contributing) and thought that pipx had the same syntax.
