### ISSUE TITLE
[Win10] [Py3.72] TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [pipxproject/pipx#95]
```
C:\Users\Nebu>pipx install tox
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pipx.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\pipx\main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "c:\python37\lib\site-packages\pipx\main.py", line 157, in run_pipx_command
    include_deps=args.include_deps,
  File "c:\python37\lib\site-packages\pipx\commands.py", line 315, in install
    if venv.get_venv_metadata_for_package(package).package_version is None:
  File "c:\python37\lib\site-packages\pipx\Venv.py", line 74, in get_venv_metadata_for_package
    stdout=subprocess.PIPE,
  File "c:\python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\python37\lib\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "c:\python37\lib\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
```

**Comment by Laurentiu-Andronache** [comment]
This was on a new installation that only had these packages installed:
```
Package    Version
---------- --------
pip        19.0.3
pipx       0.12.3.0
setuptools 40.8.0
```

**Comment by cs01** [comment]
Thank you for filing this!

Apologies for error. I don't have Windows set up in CI testing. This has been fixed in 0.12.3.1. Would you mind confirming the new version works, and if so close this issue?

(The cause of this is here: https://docs.python.org/3.7/library/subprocess.html#converting-an-argument-sequence-to-a-string-on-windows)

**Comment by Laurentiu-Andronache** [comment]
Damn, before having reported I was doing the pipx installation from repo wrong. I should have done this to install the latest version:
`pip install --upgrade git+https://github.com/pipxproject/pipx@master`

I forgot the @master at the end. Anyway, yes, it seems to work now. I was stomping my brains trying to understand the damn error (even though I don't know the processes library yet), hoping I'd submit a commit to solve it.

But I think I found another error on 0.12.3.1, and I'll try to fix that one because it's an easier one.

**Comment by cs01** [comment]
Awesome, appreciate the bug report and you taking the initiative on this!
